version: '3.8'

services:
  pdf-rag-app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - pdf_data:/app/data
    restart: unless-stopped

volumes:
  pdf_data:
