# Railway Deployment Configuration
# This file tells Railway how to deploy your app

[build]
  builder = "DOCKERFILE"

[deploy]
  healthcheckPath = "/"
  restartPolicyType = "ON_FAILURE"

[env]
  GEMINI_API_KEY = { required = true }
  NODE_ENV = "production"