name: Assert New PR Is Valid Action

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm i

      - name: Check ESLint
        run: npm run lint

      - name: Check Unit Tests
        run: npm run test:unit

      - name: Prettier Styling Check
        run: npm run format:check

      - name: Check Build
        run: npm run build
